
service: MRS

provider:
    name: aws
    runtime: nodejs6.10

functions:
    membership:
        handler: mrs.remember
        events:
            - http:
                path: remember
                method: POST
