
service: MRS

provider:
    name: aws
    runtime: nodejs8.10

functions:
    remember:
        handler: mrs.remember
        events:
            - http:
                path: remember
                method: POST
